// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXo50dMt3wONDLszgjO3vadSO9-qvpSrc',
    appId: '1:352773195094:web:2686369028080ce1a442f7',
    messagingSenderId: '352773195094',
    projectId: 'ecommerce-b6ad3',
    authDomain: 'ecommerce-b6ad3.firebaseapp.com',
    storageBucket: 'ecommerce-b6ad3.appspot.com',
    measurementId: 'G-3SHE3CX8M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_q1lzRuivWc26syJ8zq0ao6BBOQbghZU',
    appId: '1:352773195094:android:a42e8d319f08c675a442f7',
    messagingSenderId: '352773195094',
    projectId: 'ecommerce-b6ad3',
    storageBucket: 'ecommerce-b6ad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLSNNGMhOnt5m5ah7Y3jcTr3mnWKiBpN4',
    appId: '1:352773195094:ios:f5e22ce01527d988a442f7',
    messagingSenderId: '352773195094',
    projectId: 'ecommerce-b6ad3',
    storageBucket: 'ecommerce-b6ad3.appspot.com',
    iosClientId: '352773195094-am86blc0k5a1oj32p34gqhsqgbqmc56m.apps.googleusercontent.com',
    iosBundleId: 'com.thegitters.eventmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLSNNGMhOnt5m5ah7Y3jcTr3mnWKiBpN4',
    appId: '1:352773195094:ios:f5e22ce01527d988a442f7',
    messagingSenderId: '352773195094',
    projectId: 'ecommerce-b6ad3',
    storageBucket: 'ecommerce-b6ad3.appspot.com',
    iosClientId: '352773195094-am86blc0k5a1oj32p34gqhsqgbqmc56m.apps.googleusercontent.com',
    iosBundleId: 'com.thegitters.eventmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXo50dMt3wONDLszgjO3vadSO9-qvpSrc',
    appId: '1:352773195094:web:bda3d086c1928997a442f7',
    messagingSenderId: '352773195094',
    projectId: 'ecommerce-b6ad3',
    authDomain: 'ecommerce-b6ad3.firebaseapp.com',
    storageBucket: 'ecommerce-b6ad3.appspot.com',
    measurementId: 'G-64Y58EWYVL',
  );
}
